[package]
name = "ids"
version = "0.0.0-alpha.0"
edition = "2021"
description = "ğŸ‘¨ğŸ»â€ğŸ¨ Â» icons preview development server"
authors = ["Lucas Colombo <lucas@lucode.ar>"]

[profile.release]
strip = true
lto = true
codegen-units = 16
opt-level = 'z'
panic = "abort"
rpath = false
overflow-checks = false
debug = 0
debug-assertions = false

[dependencies]
eyre = { version = "0.6.12", default-features = false, features = ["auto-install"] }
indoc = "2.0.4"

[[bin]]
name = "ids"
path = "src/main.rs"
